export const BUSINESS = {
  name: "Talk N Fix Wireless",
  tagline: "Newark & Passaic's Most Trusted Same-Day Phone Repair",
  founded: 2014,
  founder: "Rey",
  reviews: "6,500+",
  repairsMonthly: "1,000+",
  avgRepairTime: "30–45 min",
  warranty: "1-Year",
};

export const LOCATIONS = [
  {
    id: "passaic-354",
    city: "Passaic",
    label: "Passaic Downtown",
    address: "354 Passaic St",
    cityStateZip: "Passaic, NJ 07055",
    note: "Parking Available",
    phone: "973-778-5900",
    hours: { weekday: "Mon–Sat: 9am – 7:45pm", weekend: "Sun: 10am – 5:45pm" },
    mapsUrl: "https://maps.google.com/?q=354+Passaic+St+Passaic+NJ+07055",
  },
  {
    id: "passaic-315",
    city: "Passaic",
    label: "Passaic Monroe",
    address: "315 Monroe St",
    cityStateZip: "Passaic, NJ 07055",
    note: "Near Shops",
    phone: "973-894-3600",
    hours: { weekday: "Mon–Sat: 9am – 7:45pm", weekend: "Sun: 10am – 5:45pm" },
    mapsUrl: "https://maps.google.com/?q=315+Monroe+St+Passaic+NJ+07055",
  },
  {
    id: "passaic-165",
    city: "Passaic",
    label: "Passaic Market",
    address: "165 Market St",
    cityStateZip: "Passaic, NJ 07055",
    note: "",
    phone: "973-767-2493",
    hours: { weekday: "Mon–Sat: 9am – 7:45pm", weekend: "Sun: 10am – 5:45pm" },
    mapsUrl: "https://maps.google.com/?q=165+Market+St+Passaic+NJ+07055",
  },
  {
    id: "newark-207",
    city: "Newark",
    label: "Newark Ironbound",
    address: "207 Ferry St",
    cityStateZip: "Newark, NJ 07105",
    note: "Ironbound Neighborhood",
    phone: "973-274-9800",
    hours: { weekday: "Mon–Sat: 9am – 7:45pm", weekend: "Sun: 10am – 5:45pm" },
    mapsUrl: "https://maps.google.com/?q=207+Ferry+St+Newark+NJ+07105",
  },
  {
    id: "newark-674",
    city: "Newark",
    label: "North Newark",
    address: "674 Mt. Prospect Ave",
    cityStateZip: "Newark, NJ 07104",
    note: "North Newark",
    phone: "973-250-6191",
    hours: { weekday: "Mon–Sat: 9am – 6:45pm", weekend: "Sun: 10am – 5:45pm" },
    mapsUrl: "https://maps.google.com/?q=674+Mt+Prospect+Ave+Newark+NJ+07104",
  },
];

export const SERVICES = [
  {
    id: "iphone-screen-repair",
    title: "iPhone Screen Repair",
    description: "Cracked or shattered display? We restore your iPhone screen to factory perfection using premium OLED/LCD assemblies.",
    time: "30–45 min",
    sameDay: true,
    popular: true,
    device: "iphone",
  },
  {
    id: "samsung-screen-repair",
    title: "Samsung Screen Repair",
    description: "Galaxy screen gone dark or cracked? We handle all Samsung models with precision and OEM-grade parts.",
    time: "30–45 min",
    sameDay: true,
    popular: true,
    device: "samsung",
  },
  {
    id: "ipad-screen-repair",
    title: "iPad Screen Repair",
    description: "Tablet screen cracked? Crystal-clear display restoration with responsive touch, same day.",
    time: "30–45 min",
    sameDay: true,
    popular: true,
    device: "ipad",
  },
  {
    id: "battery-replacement",
    title: "Battery Replacement",
    description: "Dying battery ruining your day? We swap it out fast with high-capacity OEM-spec cells.",
    time: "30 min",
    sameDay: true,
    popular: false,
    device: "all",
  },
  {
    id: "charging-port-repair",
    title: "Charging Port Repair",
    description: "Won't charge? Loose port? We clean, repair or replace charging ports on all devices.",
    time: "30–45 min",
    sameDay: true,
    popular: false,
    device: "all",
  },
  {
    id: "back-glass-repair",
    title: "Back Glass Repair",
    description: "Shattered back panel? We restore your phone's sleek look like it never happened.",
    time: "45–60 min",
    sameDay: true,
    popular: false,
    device: "iphone",
  },
  {
    id: "game-console-hdmi-repair",
    title: "Game Console HDMI",
    description: "PS5 or Xbox not displaying? We fix HDMI ports so you're back in the game fast.",
    time: "1–2 hrs",
    sameDay: true,
    popular: false,
    device: "console",
  },
  {
    id: "water-damage-repair",
    title: "Water Damage Repair",
    description: "Dropped it in water? Don't panic. Bring it in immediately — we handle liquid damage with ultrasonic cleaning.",
    time: "Same day",
    sameDay: true,
    popular: false,
    device: "all",
  },
  {
    id: "diagnostic-no-power",
    title: "Diagnostic / No Power",
    description: "Phone completely dead? We diagnose the issue and give you an honest assessment — free of charge.",
    time: "Free",
    sameDay: true,
    popular: false,
    device: "all",
  },
  {
    id: "laptop-repair",
    title: "Laptop Repair",
    description: "Screen, keyboard, battery, charging port — we fix all major laptop issues in-store.",
    time: "Same day",
    sameDay: true,
    popular: false,
    device: "laptop",
  },
  {
    id: "computer-repair",
    title: "Computer Repair",
    description: "Slow PC, virus removal, hardware upgrades — our techs handle it all.",
    time: "Same day",
    sameDay: true,
    popular: false,
    device: "computer",
  },
];

export const REVIEWS = [
  {
    name: "James R.",
    initial: "J",
    color: "bg-blue-600",
    service: "iPhone Screen Repair",
    location: "Newark NJ",
    rating: 5,
    text: "Fast and professional iPhone screen repair. Screen looks brand new, touch works perfectly. Highly recommended — in and out in 30 minutes.",
  },
  {
    name: "Maria L.",
    initial: "M",
    color: "bg-cyan-500",
    service: "Battery Replacement",
    location: "Passaic NJ",
    rating: 5,
    text: "Excellent iPhone battery replacement. Battery life improved instantly, fair pricing, quick service, friendly and knowledgeable staff.",
  },
  {
    name: "David K.",
    initial: "D",
    color: "bg-purple-600",
    service: "Samsung Screen Repair",
    location: "Passaic NJ",
    rating: 5,
    text: "Reliable Samsung screen repair. Clear display, perfect fit, fast turnaround. Professional technicians, great customer service.",
  },
  {
    name: "Sofia T.",
    initial: "S",
    color: "bg-pink-600",
    service: "Back Glass Repair",
    location: "Newark NJ",
    rating: 5,
    text: "Top-quality iPhone back glass repair. Phone looks flawless again, careful workmanship, smooth process. Very satisfied overall.",
  },
  {
    name: "Carlos M.",
    initial: "C",
    color: "bg-green-600",
    service: "Water Damage Repair",
    location: "Passaic NJ",
    rating: 5,
    text: "Had water damage and needed help fast. The team handled my phone carefully, assessed the damage, and fixed it same day. Honest and reliable.",
  },
  {
    name: "Alex P.",
    initial: "A",
    color: "bg-orange-500",
    service: "iPad Screen Repair",
    location: "Newark NJ",
    rating: 5,
    text: "Professional iPad screen repair. Quick repair, responsive touch, crystal-clear display, reasonable pricing and excellent service.",
  },
];

export const FAQS = [
  {
    q: "How much does a repair cost?",
    a: "Pricing depends on the device model and part option. Call your nearest location for an exact quote — we're always transparent about pricing before we start.",
  },
  {
    q: "How long does a repair take?",
    a: "Most repairs are completed within 30–45 minutes while you wait. Complex repairs like water damage or logic board issues may take longer.",
  },
  {
    q: "Do you offer a warranty?",
    a: "Yes — every repair includes a 1-year warranty against defects. We stand behind our work completely.",
  },
  {
    q: "Do I need an appointment?",
    a: "No appointment needed. Walk-ins are always welcome at all 5 locations.",
  },
  {
    q: "Is my data safe during repair?",
    a: "Absolutely. Standard repairs do not erase your data. We respect your privacy and never access your personal information.",
  },
  {
    q: "What brands do you repair?",
    a: "We repair iPhone, Samsung, iPad, Google, LG, Motorola, and most other major brands. We also fix laptops, computers, and game consoles.",
  },
  {
    q: "Do you use original parts?",
    a: "We use OEM-grade and premium aftermarket parts that meet or exceed original factory specifications for quality and performance.",
  },
  {
    q: "Can I wait in-store during the repair?",
    a: "Yes — most customers wait in-store while their device is repaired. Our average turnaround is 30–45 minutes.",
  },
];

export const AREAS_SERVED = [
  "Newark NJ", "Passaic NJ", "Clifton NJ", "Paterson NJ",
  "East Orange NJ", "Bloomfield NJ", "Irvington NJ", "Belleville NJ",
  "East Rutherford NJ", "Hasbrouck Heights NJ", "Wallington NJ",
  "Lodi NJ", "Kearny NJ", "Montclair NJ", "Harrison NJ",
  "Hackensack NJ", "Paramus NJ", "Elizabeth NJ",
];
